language: node_js
node_js:
  - "7"
before_install:
  - git clone https://github.com/sillyslux/fluxbox-wiki.git pages
  - cp -r _pages/* pages
script:
  - npm run-script travis-build
  - webpack --config editor/webpack.config.js
after_script:
  - git clone -b gh-pages https://github.com/sillyslux/fluxbox-wiki.git gh-pages
  - rm -r gh-pages/* && cp -r public/* gh-pages
  - cd gh-pages
  - git add --all .
  - export C_MESSAGE=${C_MESSAGE:=$TRAVIS_COMMIT_MESSAGE}
  - export GIT_COMMITTER_NAME=${C_COMMITTER_NAME:=sillyslux}
  - export GIT_COMMITTER_EMAIL=${C_COMMITTER_EMAIL:=sillyslux@net.hr}
  - export GIT_AUTHOR_NAME=${C_AUTHOR_NAME:=sillyslux}
  - export GIT_AUTHOR_EMAIL=${C_AUTHOR_EMAIL:=sillyslux@net.hr}
  - env
  - git commit -m "$C_MESSAGE" -m "build triggered from $TRAVIS_EVENT_TYPE"
  - git push https://$GITHUB_TOKEN@github.com/sillyslux/fluxbox-wiki.git gh-pages
git:
  depth: 1
branches:
  only:
  - master
