language: node_js
node_js:
  - "7"
before_install:
  - git clone https://github.com/sillyslux/fluxbox-wiki.git pages
  - cp -r _pages/* pages
script:
  - npm run-script travis-build
  - webpack --config editor/webpack.config.js
after_script:
  - env
  - git clone -b gh-pages https://github.com/sillyslux/fluxbox-wiki.git gh-pages
  - rm -r gh-pages/* && cp -r public/* gh-pages
  - cd gh-pages
  - git add --all .
  - GIT_COMMITTER_NAME="sillyslux" GIT_COMMITTER_EMAIL="sillyslux@net.hr" git commit --author "sillyslux <sillyslux@net.hr>" -m "travis $(date '+%m/%d/%y %H:%M')"
  - git push https://$GITHUB_TOKEN@github.com/sillyslux/fluxbox-wiki.git gh-pages
git:
  depth: 1
branches:
  only:
  - master
